# -*- coding: utf-8 -*-
"""Generate babeldoc_dependency_audit.json (Phase 3A, section 9)."""
import json

table_pipeline = [
    {"capability": "table bbox (layout detection)",
     "babeldoc_source_file": "babeldoc/docvision/doclayout.py::OnnxModel + format/pdf/document_il/midend/layout_parser.py::LayoutParser",
     "babeldoc_function": "handle_document/predict + process (region.box)",
     "output_fields_used_downstream": ["detected_tables[].bbox (ROI for Table Reconstruction)"],
     "replacement_available": True,
     "replacement_source": "DocLayout (Direct adapter, same ONNX model)",
     "replacement_notes": "tools/layout_direct/direct_doclayout.py reuses the identical model/weights/preprocessing/conf=0.25/names/coordinate conversion; page_013 output bit-identical to BabelDOC (IoU=1.0)."},
    {"capability": "layout class / confidence",
     "babeldoc_source_file": "layout_parser.py::process",
     "babeldoc_function": "region.class_name / region.conf",
     "output_fields_used_downstream": ["detected_tables[].label / .confidence (informational)"],
     "replacement_available": True,
     "replacement_source": "DocLayout (Direct)",
     "replacement_notes": "class_name and conf come straight from the same model output."},
    {"capability": "page dimensions",
     "babeldoc_source_file": "path_babeldoc.extract_babeldoc",
     "babeldoc_function": "doc_pdf[0].rect",
     "output_fields_used_downstream": ["none - Table Reconstruction reads PyMuPDF geometry"],
     "replacement_available": True,
     "replacement_source": "PyMuPDF",
     "replacement_notes": "identical to pymupdf page.rect; not consumed by the table branch."},
    {"capability": "text bbox",
     "babeldoc_source_file": "path_babeldoc.extract_babeldoc (pdf_paragraph)",
     "babeldoc_function": "para.box",
     "output_fields_used_downstream": ["none - table branch uses path_geometry (PyMuPDF) texts"],
     "replacement_available": True,
     "replacement_source": "PyMuPDF get_text('dict')",
     "replacement_notes": "run_reconstruct.py builds input_data.texts from extract_geometry (PyMuPDF), never from BabelDOC."},
    {"capability": "font / font size",
     "babeldoc_source_file": "path_babeldoc.extract_babeldoc (pdf_style/pdf_font)",
     "babeldoc_function": "style.font_size / font.name",
     "output_fields_used_downstream": ["none - same as above"],
     "replacement_available": True,
     "replacement_source": "PyMuPDF span font/size",
     "replacement_notes": ""},
    {"capability": "horizontal / vertical rules, rectangle/curve",
     "babeldoc_source_file": "path_babeldoc.extract_babeldoc (pdf_rectangle/pdf_curve)",
     "babeldoc_function": "r.box / c.box -> classify_primitives",
     "output_fields_used_downstream": ["none - table branch uses path_geometry (PyMuPDF get_drawings)"],
     "replacement_available": True,
     "replacement_source": "PyMuPDF get_drawings",
     "replacement_notes": ""},
    {"capability": "image / XObject",
     "babeldoc_source_file": "(not read by table branch)",
     "babeldoc_function": "-",
     "output_fields_used_downstream": ["none"],
     "replacement_available": True,
     "replacement_source": "PyMuPDF page.get_images",
     "replacement_notes": "table branch hardcodes has_image=False today."},
    {"capability": "paragraph information",
     "babeldoc_source_file": "paragraph_finder.py::ParagraphFinder",
     "babeldoc_function": "process() -> pdf_paragraph",
     "output_fields_used_downstream": ["none - table branch clusters spans itself (rows.py)"],
     "replacement_available": True,
     "replacement_source": "custom (PyMuPDF line clustering)",
     "replacement_notes": "table branch already implements its own row clustering."},
    {"capability": "formula information",
     "babeldoc_source_file": "styles_and_formulas.py::StylesAndFormulas",
     "babeldoc_function": "formula detection / protection / offset",
     "output_fields_used_downstream": ["none - table branch"],
     "replacement_available": False,
     "replacement_source": "-",
     "replacement_notes": "not needed by the table branch at all."},
]

audit = {
    "scope": "table branch (tools/table_reconstruction + tools/layout_direct + tools/table_html_render)",
    "verified_callsite": "tools/table_reconstruction/run_reconstruct.py: bab['detected_tables'] -> roi -> build_table_model",
    "table_pipeline_dependencies": table_pipeline,
    "whole_system": {
        "A_fully_replaceable": [
            {"capability": "layout detection (table bbox)",
             "where": "frontend.py LayoutParser",
             "replacement": "Direct DocLayout (same model) - proven bit-identical"},
            {"capability": "translation execution",
             "where": "ILTranslator/ILTranslatorLLMOnly via config.translator",
             "replacement": "custom DeepSeek client (pdf_translator/translation/lawai.py already the default backend)"},
        ],
        "B_replaceable_with_custom_work": [
            {"capability": "paragraph reconstruction",
             "where": "frontend.py ParagraphFinder",
             "replacement": "PyMuPDF span clustering (table branch rows.py already does this)"},
            {"capability": "reading order",
             "where": "native_parse",
             "replacement": "position-based sort (custom)"},
            {"capability": "style extraction",
             "where": "StylesAndFormulas (style part)",
             "replacement": "PyMuPDF span font/size/weight (path_geometry already extracts)"},
            {"capability": "PDF native typesetting",
             "where": "babeldoc typesetting",
             "replacement": "project HTML+Chromium pipeline (already the chosen renderer)"},
            {"capability": "IL XML/JSON serialization",
             "where": "XMLConverter",
             "replacement": "custom JSON (IL already saved as JSON)"},
        ],
        "C_keep_for_now": [
            {"capability": "formula detection",
             "where": "StylesAndFormulas",
             "reason": "specialized model + post-processing; high self-build cost"},
            {"capability": "formula protection / offset",
             "where": "StylesAndFormulas",
             "reason": "tightly coupled with formula rendering"},
            {"capability": "scanned file detection",
             "where": "DetectScannedFile",
             "reason": "cheap and already integrated"},
            {"capability": "input repair (fix_null_page_content/fix_filter/fix_null_xref/fix_media_box)",
             "where": "high_level",
             "reason": "edge-case PDF hardening; PyMuPDF equivalent needs validation"},
        ],
    },
    "multipage_test": {
        "pages_tested": [2, 4, 8, 13],
        "p2_plain_no_table": {"direct_tables": 0, "false_positive": False},
        "p4_grid_geometry": {
            "direct_tables": 0, "babeldoc_tables": 0,
            "note": "both paths classify this full-grid table as figure (DocLayout docstructbench model behaviour); full-grid table sample effectively MISSING in this test PDF",
            "grid_extent": [88.0, 104.6, 353.4, 239.6],
            "figure_bbox": [81.0, 73.89, 516.0, 259.89]},
        "p8_grid_geometry": {
            "direct_tables": 0,
            "note": "same as p4: classified figure by both paths"},
        "p13_sparse_rule": {
            "direct_tables": 1, "babeldoc_tables": 1, "bbox_identical": True,
            "bbox": [70.0, 68.89, 526.0, 229.89], "iou": 1.0},
    },
    "verdict": {
        "table_branch_babeldoc_removable": True,
        "criterion": "IoU>=0.98 AND row/column/cell count match AND cell text exact=1.0",
        "page13_result": {
            "iou": 1.0, "row_count_match": True, "column_count_match": True,
            "cell_count_match": True, "cell_text_exact_match_ratio": 1.0,
            "table_type_match": True},
        "caveats": [
            "full-grid table sample absent in this PDF (DocLayout labels them figure); table branch only proven for sparse_rule via either path",
            "BabelDOC still provides: formula protection + paragraph/reading-order infra + scanned detection + input repair for the FULL pipeline",
            "removing BabelDOC from the table branch does NOT remove it from the whole system",
        ],
    },
}

with open("runs/fyresults/recon_2504_p13/babeldoc_dependency_audit.json",
          "w", encoding="utf-8") as f:
    json.dump(audit, f, ensure_ascii=False, indent=2)
print("wrote babeldoc_dependency_audit.json")
print("verdict:", json.dumps(audit["verdict"], ensure_ascii=False))
